# Generated by Django 4.0 on 2022-03-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_card',
            name='phone',
            field=models.CharField(default='00', max_length=255),
        ),
        migrations.AddField(
            model_name='profile_card',
            name='place',
            field=models.CharField(default='non', max_length=255),
        ),
    ]
